world:
  dimensions: [100, 100, 50]
  num_drones: 10
  num_buildings: 20
  coverage_resolution: 1.0

drone:
  max_velocity: 10.0
  max_acceleration: 5.0
  battery_capacity: 100.0
  communication_range: 50.0

pso:
  inertia_weight: 0.7
  cognitive_weight: 1.5
  social_weight: 1.5
  max_velocity: 10.0

rl:
  learning_rate: 0.0001
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  memory_size: 10000
  batch_size: 64
  hidden_dim: 256

training:
  num_episodes: 1000
  max_steps: 1000
  target_coverage: 0.9
  update_target_freq: 100
  save_freq: 50